name: CI

on:
  push:
    branches:
    - 'main'
    - 'develop'
    - 'feature/**'
  pull_request:
    branches:
    - 'main'
    - 'develop'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Install Linter
        run: make lint-install

      - name: Verify Go modules
        run: go mod tidy && git diff --exit-code

      - name: Lint
        run: make lint

      - name: Run All Tests
        run: make test-all

      - name: Build macOS CLI
        run: make cli-macos

      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.out